### ISSUE TITLE
xtx endpoint needs to be updated

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/spacyapp#1]
The new endpoint of the xtx tokenizer has changed to `https://xtx.acdh.oeaw.ac.at/exist/restxq/xtoks/tokenize/default` 

https://github.com/acdh-oeaw/spacyapp/blob/0ca7e31ec821eca06c187a89ecd7a56c0ca64b07/enrich/api_views.py#L172

**Comment by csae8092** [comment]
import xtx endpoint from settings file

**Comment by sennierer** [comment]
changed the url, but still an error in nlp chain endpoint.
